kendaraan =["b 4030 rfs","beat","150","black"]
kendaraan.append("30 juta")
kendaraan.append("2 roda")
kendaraan.insert(2,"honda")
kendaraan.insert(3,"motor matic")
print(kendaraan [0])
print(kendaraan [1])
print(kendaraan [2])
print(kendaraan [3])
print(kendaraan [4])
print(kendaraan [5])
print(kendaraan [6])
print(kendaraan [7])